---
title: "UNIX COMMANDS"
author: Sébastien Renaut
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    highlight: tango
    number_sections: F
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Exploration commands
Command | Meaning
------------- | ----------------------------------------------------
`ls` | what's there
`ls -1` | with an option 
`ls -t -h` | with more options  
`ls -thor` | combining even more options
`man ls` | manual: what are the options (q = quit; d = next page; ; arrows & fn arrows = scrolling)  
`pwd`| where are we (full path)  
`cd` | move somewhere else (default to home)   
`cd ..` | move back  
`cd ../Applications` | move back, then forward  
`cd ~ ` | move home 
`cd /` | move to root    

#General principles  
• All commands are short, perform simple tasks & are highly optimized (fast)  
• Nearly all commands and options (~99%) work across Unix-based OS
• Commands can take (many) options  
• Commands can be combined (the pipe `|`)  
• Many commands don't require any argument, some do  
• `command -option1 -option2 -optionN... parameter object`
• Many commands write output to terminal (redirected using `>`)

#Moving / removing / creating files
Command | Meaning
------------- | ----------------------------------------------------
`mv` |move  
`cp` |copy  
`rm` |careful remove  
`rmdir` |*careful* remove empty directory  
`rm -r` |*VERY careful*.. remove recursively
`mkdir` |create empty directory 
`touch` |create empty file  
`echo` |Print message to screen 

#Examining files
Command | Meaning
------------- | ----------------------------------------------------
`head` |Print first 10 lines to screen  
`tail` |Print laste 10 lines to screen    
`less` |Print file line by line (use arrows + fn arrows to move up/down)
`cat` |Print file content to screen 
`sort` |Sort a file
`uniq` |unique lines in a file  
`clear` |clear terminal
`wc` |wordcount  

#Tricks
Command | Meaning
------------- | ----------------------------------------------------
`>` |the redirect
`>>` |the redirect (append to file)
`|` |the pipe   
`*` |anything (special character: for literal `*`, use `\*`)  
`?` |anyone character (special character)  
`Ctrl+A` |go to beginning of line in terminal    
`Ctrl+E` |end of line    
`tab key`| autocomplete

#Working remotely
Command | Meaning
------------- | ----------------------------------------------------
`ssh` |secure shell (remote connection)  
`scp`  |secure copy (remote connection)  

#Other useful commands
Command | Meaning
------------- | ----------------------------------------------------
`chmod` |change mode of file
`sudo` |superuser do  
`top` |who is running what?
`kill` |kill a process   
`curl` |get stuff from web (MACOS native) or `wget` (MACOS non-native)  
`history` |see recent history     
`open` | open a file   
`ln` | symbolic link  
`which` |where is the command
`alias` |create own commands 
`nano` | edit text (whole file loaded in memory)      
`nano +123` |specify location  

#Profile
• Let's look at .bash_profile to modify options (e.g. `nano ~/.bash_profile`)

#Compression
Command | Meaning
------------- | ----------------------------------------------------
`gzip`  |compression/decompression of files  
`gzip -cd file.gz`  |decompress to standard out (use a `>` redirect) 
`gunzip`  |compression/decompression of files  
`tar`  |compression/decompression of archives  
`tar -xvzf file tar.gz` |decompress a tar.gz (tarball)  

#Regular expressions
Command | Meaning
------------- | ----------------------------------------------------
`grep` -options 'pattern' file |#regular expressions  

#Combining commands
• Let's look at the file `examples/sequence.fasta`  
• print line 17 piping `head` and `tail`  
• Count lines starting with '>'  
• Count unique lines starting with '>'  

#Install and run command line programs
• Let's look at this example:   https://github.com/rec3141/rec-genome-tools/blob/master/bin/fastagrep.pl  
• It is a short `perl` script that greps sequences in a *.fasta* file  
• Copy-paste the text in a new file (e.g. `touch fastagrep.pl`,`nano fastagrep.pl`,paste and save)   
• Make it executable (`chmod +x`)    
• Let's look at it (`./fastagrep.pl`)  
• Let's try it (`./fastagrep.pl 'deserticola' examples/sequence.fasta`)  
• Let's symbolic link it so the computer knows where to find it (` ln /Users/jerry/Dropbox/CSBQ/workshop/unix_workshop_2018/fastagrep.pl /usr/local/bin/fastagrep.pl`)  
  
#bash
`bash`  (let's look at an example `less examples/bash_cmd2`)



